SIS_Ga2/Controllers/ContactoController.cs
using SIS_Ga2.Business;
using SIS_Ga2.Entity;
using SIS_Ga2.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;

namespace SIS_Ga2.Controllers
{
    public class ContactoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public string SendEmail(ContactoModel contacto)
        {
            try
            {

                string EmailOrigen = string.IsNullOrEmpty(ConfigurationManager.AppSettings["CorreoRemitente"]) ? throw new Exception("Parametro correo remitente no encontrado") : ConfigurationManager.AppSettings["CorreoRemitente"];
                string EmailDestino = string.IsNullOrEmpty(ConfigurationManager.AppSettings["CorreoDestino"]) ? throw new Exception("Parametro correo remitente no encontrado") : ConfigurationManager.AppSettings["CorreoDestino"];
                string Contrasena = string.IsNullOrEmpty(ConfigurationManager.AppSettings["ClaveRemitente"]) ? throw new Exception("Parametro clave remitente no encontrado") : ConfigurationManager.AppSettings["ClaveRemitente"];
                string smtpserver = string.IsNullOrEmpty(ConfigurationManager.AppSettings["SMTPServer"]) ? throw new Exception("Parametro servidor correo no encontrado") : ConfigurationManager.AppSettings["SMTPServer"];
                string smtpport = string.IsNullOrEmpty(ConfigurationManager.AppSettings["SMTPPort"]) ? throw new Exception("Parametro puerto servidor correo no encontrado") : ConfigurationManager.AppSettings["SMTPPort"];
                string enablessl = string.IsNullOrEmpty(ConfigurationManager.AppSettings["EnableSSL"]) ? "false" : ConfigurationManager.AppSettings["EnableSSL"];

                var cuerpohtml = ConstantesRecursos.CorreoContacto;

                cuerpohtml = cuerpohtml.Replace("[Nombre]", contacto.Nombre);
                cuerpohtml = cuerpohtml.Replace("[Mensaje]", contacto.Mensaje);
                cuerpohtml = cuerpohtml.Replace("[Correo]", contacto.Correo);
                cuerpohtml = cuerpohtml.Replace("[Telefono]", contacto.Telefono);

                var asunto = string.IsNullOrEmpty(contacto.Asunto) ? "CONSULTAS FORMULARIO CONTACTO" : contacto.Asunto;

                ServicePointManager.Expect100Continue = true;
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                       | SecurityProtocolType.Tls11
                       | SecurityProtocolType.Tls12
                       | SecurityProtocolType.Ssl3;


                MailMessage oMailMessage = new MailMessage(EmailOrigen, EmailDestino,asunto, cuerpohtml);
                oMailMessage.IsBodyHtml = true;

                SmtpClient oSmtpClient = new SmtpClient(smtpserver);

                oSmtpClient.Port = Convert.ToInt32(smtpport);
                oSmtpClient.EnableSsl = Convert.ToBoolean(enablessl);
                oSmtpClient.UseDefaultCredentials = false;
                oSmtpClient.Credentials = new System.Net.NetworkCredential(EmailOrigen, Contrasena);
                oSmtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;

                oSmtpClient.Send(oMailMessage);
                oSmtpClient.Dispose();

                return "Se he enviado correctamente el correo de contacto";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }

            
        }

    }
}

SIS_Ga2/Controllers/UsuarioController.cs
using SIS_Ga2.Business;
using SIS_Ga2.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SIS_Ga2.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            var lstestado = new List<SelectListItem>
            {
                new SelectListItem { Text = "TODOS", Value = "" },
                new SelectListItem { Text = "ACTIVO", Value = "1" },
                new SelectListItem { Text = "INACTIVO", Value = "0" }
            };
            ViewData["ddlEstado"] = lstestado;

            return View();
        }

        public ActionResult MantenimientoNuevo()
        {
            Session["usuario.mant"] = new BEUsuario();
            return View("Mantenimiento");
        }

        public ActionResult MantenimientoEditar(int idusuario)
        {
            var bLusuario = new BLusuario();
            var lista = bLusuario.ListarUsuario(new BEUsuario());

            var usuario = lista.Find(x => x.Id_Usuario == idusuario);

            Session["usuario.mant"] = usuario;

            return View("Mantenimiento");
        }

        public JsonResult ListarUsuario(BEUsuario usuario)
        {
            var bLusuario = new BLusuario();
            var lista = bLusuario.ListarUsuario(usuario);

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GrabarDatos(BEUsuario usuario)
        {
            try
            {
                var bLusuario = new BLusuario();
                bLusuario.GrabarDatos(usuario);

                return Json(new { data = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { data = "ERROR" }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ObtenerDatos(int idusuario)
        {
            var bLusuario = new BLusuario();
            var lista = bLusuario.ListarUsuario(new BEUsuario());

            var usuario = lista.Find(x => x.Id_Usuario == idusuario);

            return Json(new { data = usuario }, JsonRequestBehavior.AllowGet);

        }

        public JsonResult EliminarUsuario(int IdUsuarioSesion, int IdUsuarioDelete, string estado)
        {
            try
            {
                var iestado = estado == "0" ? 1 : 0;

                var bLusuario = new BLusuario();
                bLusuario.EliminarUsuario(new BEUsuario { Id_Usuario = IdUsuarioDelete, Usr_Actualizacion = IdUsuarioSesion.ToString(), Estado = iestado });

                return Json(new { data = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { data = "ERROR" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SIS_Ga2/Views/Shared/_Layout.cshtml
@using SIS_Ga2.Entity

@{

    ViewBag.Title = "Proyecto";
    BEUsuario usuario = Session["sistema.usuario"] as BEUsuario;
    Sistema sistema = Session["sistema.general"] as Sistema;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ASOCEM – Proyecto AASHTO</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="all,follow">



    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="~/Content/fontastic.css">
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/Content/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/Content/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/Content/img/favicon.ico">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <style>

        nav.side-navbar ul li.active > a {
            background: #6bb435 !important;
            border-left: 4px solid #6bb435 !important;
        }

        .btn-outline-primary {
            color: #6bb435 !important;
            background-color: transparent;
            background-image: none;
            border-color: #6bb435 !important;
        }

            .btn-outline-primary:hover {
                color: #fff !important;
                background-color: #6bb435 !important;
                border-color: #6bb435 !important;
            }

        .btn-primary {
            background-color: #6bb435 !important;
            border-color: #6bb435 !important;
        }

            .btn-primary:hover {
                background-color: #006548 !important;
                border-color: #006548 !important;
            }

            .btn-primary:focus, .btn-primary.focus {
                -webkit-box-shadow: 0 0 0 0.2rem #006548 !important;
                box-shadow: 0 0 0 0.2rem #006548 !important;
            }
    </style>

</head>
<body>
    <div class="page">
        <!-- Main Navbar-->
        <header class="header">
            <nav class="navbar" style="background:#006548;">
                <!-- Search Box-->
                <div class="container-fluid">
                    <div class="navbar-holder d-flex align-items-center justify-content-between">
                        <!-- Navbar Header-->
                        <div class="navbar-header col-lg-6">
                            <!-- Navbar Brand -->
                            @if (usuario != null && usuario.Id_Cargo == 4)
                            {
                                <a href="@Url.Action("Index", "Usuario")" class="navbar-brand d-none d-sm-inline-block">
                                    <div class="brand-text d-none d-lg-inline-block">
                                        @*<strong>ASOCEM</strong><p style="font-size:small">ASOCIACIÓN DE PRODUCTORES DE CEMENTO</p>*@
                                        <img src="~/Content/images/logo_neuvo_asocem.jpg" style="max-height: 100%; max-width: 20%" />
                                    </div>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("Index", "Home")" class="navbar-brand d-none d-sm-inline-block">
                                    <div class="brand-text d-none d-lg-inline-block">
                                        @*<strong>ASOCEM</strong><p style="font-size:small">ASOCIACIÓN DE PRODUCTORES DE CEMENTO</p>*@
                                        <img src="~/Content/images/logo_neuvo_asocem.jpg" style="max-height:100%; max-width:20%" />
                                    </div>
                                </a>
                            }
                            <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active" style="display:none"><span></span><span></span><span></span></a>
                        </div>

                        <!-- Navbar Menu -->
                        <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-lg-end">
                            <li class="nav-item"><a href="@Url.Action("Index", "Contacto" )" class="nav-link"> <span class="d-none d-sm-inline">Contacto&nbsp;&nbsp;&nbsp;</span><i class="fa fa-user"></i></a></li>
                            <li class="nav-item"><a href="@Url.Action("Logout", "Seguridad" )" class="nav-link logout"> <span class="d-none d-sm-inline">Salir</span><i class="fa fa-sign-out"></i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="page-content d-flex align-items-stretch">
            <!-- Side Navbar -->
            <nav id="sidebar" class="side-navbar">
                <!-- Sidebar Header-->
                <div class="sidebar-header d-flex align-items-center">
                    <div class="avatar"><img src="~/Content/icon/img_user_3.png" alt="..." class="img-fluid rounded-circle"></div>
                    <div class="title">
                        @if (usuario != null)
                        {
                            <h1 class="h4">@usuario.Usuario</h1>
                            <p>@usuario.Apellido</p>
                        }
                    </div>
                </div>
                <!-- Sidebar Navidation Menus--><span class="heading">Menú</span>
                <ul class="list-unstyled">
                    @if (usuario != null && usuario.Id_Cargo == 4)
                    {
                        <li class="active"><a href="@Url.Action("Index", "Usuario")"> <i class="icon-grid"></i>Dashboard</a></li>
                    }
                    else
                    {
                        <li class="active"><a href="@Url.Action("Index", "Home")"> <i class="icon-grid"></i>Dashboard</a></li>
                    }
                </ul>
            </nav>
            <div class="content-inner" style="background: rgba(237,237,237,0.7);">
                <!-- Page Header-->
                <header class="page-header">
                    <div class="container-fluid">
                        @if (usuario != null)
                        {
                            <h2 class="no-margin-bottom lead">Hola @usuario.Nombre, Bienvenido.!</h2>
                        }
                    </div>


                </header>
                <!-- Dashboard Counts Section-->
                <section class="dashboard-counts no-padding-bottom">
                    @RenderBody()

                </section>
                <!-- Page Footer-->
                <br>
            </div>
        </div>
    </div>
    <footer style="background-color:black; height:9em;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6" style="margin-left: 5em;">
                    <a href="http://www.asocem.org.pe/" class="navbar-brand d-none d-sm-inline-block" style="color:white">
                        <span>&nbsp;&nbsp; www.asocem.org.pe</span>
                    </a>
                    <div class="brand-text">
                        <img src="~/Content/images/logo_neuvo_asocem.jpg" style="width: auto; height: 5em;" />
                    </div>
                </div>
                <div class="col-sm-6 text-right">
                </div>
            </div>
        </div>

    </footer>
    <!-- JavaScript files-->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>


    <!-- Include Bootstrap Datepicker V2 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/es.js"></script>


    <link rel="stylesheet" href="~/Content/Repo/bootstrap-material-datetimepicker-bs4.min.css">
    <script src="~/Content/Repo/bootstrap-material-datetimepicker-bs4.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>


    <script type="text/javascript">
        $(function () {

            //$("#datetimepicker1").datepicker();
            //$("#datetimepicker2").datepicker();

            $('#datetimepicker1').bootstrapMaterialDatePicker({
                format: 'DD/MM/YYYY',
                shortTime: false,
                date: true,
                time: false,
                monthPicker: false,
                year: false,
                clearButton: true,
                nowButton: false,
                switchOnClick: true,
                cancelText: 'Cancelar',
                clearText: 'Limpiar',
                okText: 'OK',
                triggerEvent: 'focus',
                lang: 'es',
                weekStart: 1,

            });

            $('#datetimepicker2').bootstrapMaterialDatePicker({
                format: 'DD/MM/YYYY',
                shortTime: false,
                date: true,
                time: false,
                monthPicker: false,
                year: false,
                clearButton: true,
                nowButton: false,
                switchOnClick: true,
                cancelText: 'Cancelar',
                clearText: 'Limpiar',

                okText: 'OK',
                triggerEvent: 'focus',
                lang: 'es',
                weekStart: 1,

            });



        });

    </script>



</body>
</html>

SIS_Ga2/Views/Shared/_LayoutNoMenu.cshtml
@using SIS_Ga2.Entity

@{

    ViewBag.Title = "Proyecto";
    BEUsuario usuario = Session["sistema.usuario"] as BEUsuario;
    Sistema sistema = Session["sistema.general"] as Sistema;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ASOCEM – Proyecto AASHTO</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="all,follow">



    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="~/Content/fontastic.css">
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/Content/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/Content/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/Content/img/favicon.ico">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">

    <style>

        nav.side-navbar ul li.active > a {
            background: #6bb435 !important;
            border-left: 4px solid #6bb435 !important;
        }

        .btn-outline-primary {
            color: #6bb435 !important;
            background-color: transparent;
            background-image: none;
            border-color: #6bb435 !important;
        }

            .btn-outline-primary:hover {
                color: #fff !important;
                background-color: #6bb435 !important;
                border-color: #6bb435 !important;
            }

        .btn-primary {
            background-color: #6bb435 !important;
            border-color: #6bb435 !important;
        }

            .btn-primary:hover {
                background-color: #006548 !important;
                border-color: #006548 !important;
            }

            .btn-primary:focus, .btn-primary.focus {
                -webkit-box-shadow: 0 0 0 0.2rem #006548 !important;
                box-shadow: 0 0 0 0.2rem #006548 !important;
            }
    </style>

</head>
<body>
    <div class="page">
        <!-- Main Navbar-->
        <header class="header">
            <nav class="navbar" style="background:#006548;">
                <!-- Search Box-->
                <div class="container-fluid">
                    <div class="navbar-holder d-flex align-items-center justify-content-between">
                        <!-- Navbar Header-->
                        <div class="navbar-header col-lg-6">
                            <!-- Navbar Brand -->
         
                            <a href="@Url.Action("Index", "Home")" class="navbar-brand d-none d-sm-inline-block">
                                <div class="brand-text d-none d-lg-inline-block">
                                    @*<strong>ASOCEM</strong><p style="font-size:small">ASOCIACIÓN DE PRODUCTORES DE CEMENTO</p>*@
                                    <img src="~/Content/images/logo_neuvo_asocem.jpg" style="max-height:100%; max-width:20%" />
                                </div>
                            </a>
                            
                            <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active" style="display:none"><span></span><span></span><span></span></a>
                        </div>

                        <!-- Navbar Menu -->
                        <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-lg-end">
                            <li class="nav-item"><a href="@Url.Action("Logout", "Seguridad" )" class="nav-link logout"> <span class="d-none d-sm-inline">Salir</span><i class="fa fa-sign-out"></i></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="page-content d-flex align-items-stretch">
            <!-- Side Navbar -->

            <div class="content-inner" style="width:100% !important; background: rgba(237,237,237,0.7);">
                <!-- Page Header-->
                <header class="page-header">
                    <div class="container-fluid">
                        @if (usuario != null)
                        {
                            <h2 class="no-margin-bottom lead">Hola @usuario.Nombre, Bienvenido.!</h2>
                        }
                    </div>
                </header>
                <!-- Dashboard Counts Section-->
                <section class="dashboard-counts no-padding-bottom">

                    @RenderBody()

                </section>
                <!-- Page Footer-->
                <br>
            </div>
        </div>
    </div>
    <footer style="background-color:black; height:9em;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6" style="margin-left: 5em;">
                    <a href="http://www.asocem.org.pe/" class="navbar-brand d-none d-sm-inline-block" style="color:white">
                        <span>&nbsp;&nbsp; www.asocem.org.pe</span>
                    </a>
                    <div class="brand-text">
                        <img src="~/Content/images/logo_neuvo_asocem.jpg" style="width: auto; height: 5em;" />
                    </div>
                </div>
                <div class="col-sm-6 text-right">
                </div>
            </div>
        </div>

    </footer>
    <!-- JavaScript files-->

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>


    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>


    <!-- Include Bootstrap Datepicker V2 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/es.js"></script>


    <link rel="stylesheet" href="~/Content/Repo/bootstrap-material-datetimepicker-bs4.min.css">
    <script src="~/Content/Repo/bootstrap-material-datetimepicker-bs4.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>


    <script type="text/javascript">
        $(function () {

            //$("#datetimepicker1").datepicker();
            //$("#datetimepicker2").datepicker();

            $('#datetimepicker1').bootstrapMaterialDatePicker({
                format: 'DD/MM/YYYY',
                shortTime: false,
                date: true,
                time: false,
                monthPicker: false,
                year: false,
                clearButton: true,
                nowButton: false,
                switchOnClick: true,
                cancelText: 'Cancelar',
                clearText: 'Limpiar',
                okText: 'OK',
                triggerEvent: 'focus',
                lang: 'es',
                weekStart: 1,

            });

            $('#datetimepicker2').bootstrapMaterialDatePicker({
                format: 'DD/MM/YYYY',
                shortTime: false,
                date: true,
                time: false,
                monthPicker: false,
                year: false,
                clearButton: true,
                nowButton: false,
                switchOnClick: true,
                cancelText: 'Cancelar',
                clearText: 'Limpiar',

                okText: 'OK',
                triggerEvent: 'focus',
                lang: 'es',
                weekStart: 1,

            });



        });

    </script>



</body>
</html>