SIS_Ga2/Controllers/ParametrosAdoquinController.cs
using Newtonsoft.Json;
using SIS_Ga2.Business;
using SIS_Ga2.Entity;
using SIS_Ga2.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;

namespace SIS_Ga2.Controllers
{
    public class ParametrosAdoquinController : Controller
    {
        // GET: ParametrosAdoquin
        public ActionResult Index()
        {

            string IdDis = Session["DisenoId"] == null ? "0" : Session["DisenoId"]?.ToString();

            List<SelectListItem> lstPeriodoDiseno = new List<SelectListItem>();
            lstPeriodoDiseno.Add(new SelectListItem() { Text = "5.00", Value = "1" });
            lstPeriodoDiseno.Add(new SelectListItem() { Text = "10.00", Value = "2" });
            lstPeriodoDiseno.Add(new SelectListItem() { Text = "15.00", Value = "3" });
            lstPeriodoDiseno.Add(new SelectListItem() { Text = "20.00", Value = "4" });
            ViewData["ddlPeriodoDisenoParam"] = lstPeriodoDiseno;


            BLTasaCrecimiento objblTasaCrecimiento = new BLTasaCrecimiento();
            List<SelectListItem> data_list = new List<SelectListItem>();
            data_list.AddRange(objblTasaCrecimiento.ListarTasaCrecimiento(0).Select(a => new SelectListItem() { Text = a.TasaCrecimiento.ToUpper(), Value = Convert.ToString(a.IdTasaCrecimiento) }));
            ViewData["ddlTasaCrecimiento"] = data_list;



            BLPropFactorDistribucion objblPropFactorDistribucion = new BLPropFactorDistribucion();
            List<SelectListItem> data_list_2 = new List<SelectListItem>();
            data_list_2.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(1).Select(a => new SelectListItem() { Text = a.Numero_Calzada.ToString(), Value = Convert.ToString(a.Numero_Calzada) }));
            ViewData["ddlCalzada"] = data_list_2;

            List<SelectListItem> data_list_3 = new List<SelectListItem>();
            data_list_3.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(3).Select(a => new SelectListItem() { Text = a.Numero_Carril_x_Sentido.ToString(), Value = Convert.ToString(a.Numero_Carril_x_Sentido) }));
            ViewData["ddlCarrilxSentido"] = data_list_3;

            List<SelectListItem> data_list_4 = new List<SelectListItem>();
            data_list_4.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(2).Select(a => new SelectListItem() { Text = a.Numero_Sentido.ToString(), Value = Convert.ToString(a.Numero_Sentido) }));
            ViewData["ddlNumSentido"] = data_list_4;




            BLTipoVehiculo objblTipoVehiculo = new BLTipoVehiculo();
            List<SelectListItem> lstTipoVehiculo = new List<SelectListItem>();
            lstTipoVehiculo.AddRange(objblTipoVehiculo.ListarTipoVehiculos(0).Select(a => new SelectListItem() { Text = a.Tipo_Vehiculo.ToString(), Value = Convert.ToString(a.Id_Tipo_Vehiculo) }));
            ViewData["ddlTipoVehiculo"] = lstTipoVehiculo;
            ViewData["ddlTasaTipoVehiculo"] = lstTipoVehiculo;


            List<SelectListItem> lstVehiculo = new List<SelectListItem>();
            lstVehiculo.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            ViewData["ddlVehiculo"] = lstVehiculo;

            List<SelectListItem> lstTipoEje_1 = new List<SelectListItem>();
            lstTipoEje_1.Add(new SelectListItem() { Text = " ", Value = "0" });
            ViewData["ddlTipoEje_1"] = lstTipoEje_1;

            List<SelectListItem> lstTipoEje_2 = new List<SelectListItem>();
            lstTipoEje_2.Add(new SelectListItem() { Text = " ", Value = "0" });
            ViewData["ddlTipoEje_2"] = lstTipoEje_2;

            List<SelectListItem> lstTipoEje_3 = new List<SelectListItem>();
            lstTipoEje_3.Add(new SelectListItem() { Text = " ", Value = "0" });
            ViewData["ddlTipoEje_3"] = lstTipoEje_3;

            List<SelectListItem> lstTipoEje_4 = new List<SelectListItem>();
            lstTipoEje_4.Add(new SelectListItem() { Text = " ", Value = "0" });
            ViewData["ddlTipoEje_4"] = lstTipoEje_4;

            List<SelectListItem> lstTipoEje_5 = new List<SelectListItem>();
            lstTipoEje_5.Add(new SelectListItem() { Text = " ", Value = "0" });
            ViewData["ddlTipoEje_5"] = lstTipoEje_5;


            List<SelectListItem> lstCalidadDrenaje = new List<SelectListItem>();
            lstCalidadDrenaje.Add(new SelectListItem() { Text = "Excelente", Value = "1" });
            lstCalidadDrenaje.Add(new SelectListItem() { Text = "Bueno", Value = "2" });
            lstCalidadDrenaje.Add(new SelectListItem() { Text = "Regular", Value = "3" });
            lstCalidadDrenaje.Add(new SelectListItem() { Text = "Pobre", Value = "4" });
            lstCalidadDrenaje.Add(new SelectListItem() { Text = "Malo", Value = "5" });
            ViewData["ddlCalidadDrenaje"] = lstCalidadDrenaje;


            List<SelectListItem> lstCalidadDrenajeSubBase = new List<SelectListItem>();
            lstCalidadDrenajeSubBase.Add(new SelectListItem() { Text = "Excelente", Value = "1" });
            lstCalidadDrenajeSubBase.Add(new SelectListItem() { Text = "Bueno", Value = "2" });
            lstCalidadDrenajeSubBase.Add(new SelectListItem() { Text = "Regular", Value = "3" });
            lstCalidadDrenajeSubBase.Add(new SelectListItem() { Text = "Pobre", Value = "4" });
            lstCalidadDrenajeSubBase.Add(new SelectListItem() { Text = "Malo", Value = "5" });
            ViewData["ddlCalidadDrenajeSubBase"] = lstCalidadDrenajeSubBase;


            BLCoefEspesor objblCoefEspesor = new BLCoefEspesor();
            List<SelectListItem> lstEspesor = new List<SelectListItem>();
            lstEspesor.AddRange(objblCoefEspesor.ListaCoefEspesor().Select(a => new SelectListItem() { Text = a.Espesor.ToString(), Value = Convert.ToString(a.Id_Espesor) }));
            ViewData["ddlEspesor"] = lstEspesor;

            BLCoefPresion objblCoefPresion = new BLCoefPresion();
            List<SelectListItem> lstPresion = new List<SelectListItem>();
            lstPresion.AddRange(objblCoefPresion.ListaCoefPresion().Select(a => new SelectListItem() { Text = a.Presion.ToString(), Value = Convert.ToString(a.Id_Presion) }));
            ViewData["ddlPresion"] = lstPresion;


            return PartialView();
        }

        public PartialViewResult IndexAdoquin()
        {
            return PartialView("_Index");
        }

        public PartialViewResult ParamDisenoAdoquin()
        {
            return PartialView("_ParamDiseno");
        }

        public PartialViewResult VariableDisenoAdoquin()
        {

            var lstPeriodoDiseno = new List<SelectListItem>
            {
                new SelectListItem() { Text = "5.00", Value = "1" },
                new SelectListItem() { Text = "10.00", Value = "2" },
                new SelectListItem() { Text = "15.00", Value = "3" },
                new SelectListItem() { Text = "20.00", Value = "4" }
            };
            ViewData["ddlPeriodoDisenoParam"] = lstPeriodoDiseno;


            BLTasaCrecimiento objblTasaCrecimiento = new BLTasaCrecimiento();
            List<SelectListItem> data_list = new List<SelectListItem>();
            data_list.AddRange(objblTasaCrecimiento.ListarTasaCrecimiento(0).Select(a => new SelectListItem() { Text = a.TasaCrecimiento.ToUpper(), Value = Convert.ToString(a.IdTasaCrecimiento) }));
            ViewData["ddlTasaCrecimiento"] = data_list;

            BLPropFactorDistribucion objblPropFactorDistribucion = new BLPropFactorDistribucion();
            List<SelectListItem> data_list_2 = new List<SelectListItem>();
            data_list_2.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(1).Select(a => new SelectListItem() { Text = a.Numero_Calzada.ToString(), Value = Convert.ToString(a.Numero_Calzada) }));
            ViewData["ddlCalzada"] = data_list_2;

            List<SelectListItem> data_list_3 = new List<SelectListItem>();
            data_list_3.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(3).Select(a => new SelectListItem() { Text = a.Numero_Carril_x_Sentido.ToString(), Value = Convert.ToString(a.Numero_Carril_x_Sentido) }));
            ViewData["ddlCarrilxSentido"] = data_list_3;

            List<SelectListItem> data_list_4 = new List<SelectListItem>();
            data_list_4.AddRange(objblPropFactorDistribucion.ListarFactorDistribucion(2).Select(a => new SelectListItem() { Text = a.Numero_Sentido.ToString(), Value = Convert.ToString(a.Numero_Sentido) }));
            ViewData["ddlNumSentido"] = data_list_4;

            BLCoefEspesor objblCoefEspesor = new BLCoefEspesor();
            List<SelectListItem> lstEspesor = new List<SelectListItem>();
            lstEspesor.AddRange(objblCoefEspesor.ListaCoefEspesor().Select(a => new SelectListItem() { Text = a.Espesor.ToString(), Value = Convert.ToString(a.Id_Espesor) }));
            ViewData["ddlEspesor"] = lstEspesor;

            BLCoefPresion objblCoefPresion = new BLCoefPresion();
            List<SelectListItem> lstPresion = new List<SelectListItem>();
            lstPresion.AddRange(objblCoefPresion.ListaCoefPresion().Select(a => new SelectListItem() { Text = a.Presion.ToString(), Value = Convert.ToString(a.Id_Presion) }));
            ViewData["ddlPresion"] = lstPresion;

            BLTipoVehiculo objblTipoVehiculo = new BLTipoVehiculo();
            List<SelectListItem> lstTipoVehiculo = new List<SelectListItem>();
            lstTipoVehiculo.AddRange(objblTipoVehiculo.ListarTipoVehiculos(0).Select(a => new SelectListItem() { Text = a.Tipo_Vehiculo.ToString(), Value = Convert.ToString(a.Id_Tipo_Vehiculo) }));
            ViewData["ddlTipoVehiculo"] = lstTipoVehiculo;
            ViewData["ddlTasaTipoVehiculo"] = lstTipoVehiculo;

            List<SelectListItem> lstVehiculo = new List<SelectListItem>();
            lstVehiculo.Add(new SelectListItem() { Text = "Seleccione", Value = "0" });
            ViewData["ddlVehiculo"] = lstVehiculo;

SIS_Ga2/Controllers/ProyectoDisenoController.cs
using SIS_Ga2.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SIS_Ga2.Controllers
{
    public class ProyectoDisenoController : Controller
    {
        // GET: ProyectoDiseno

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult DatosProyecto()
        {

            List<SelectListItem> lstReglamento = new List<SelectListItem>
            {
                new SelectListItem() { Text = "Manual de Carreteras MTC", Value = "1" },
                new SelectListItem() { Text = "Pavimentos Urbanos CE. 010", Value = "2" }
            };
            ViewData["ddlReglamento"] = lstReglamento;


            BLDepartamento objblDepartamento = new BLDepartamento();
            List<SelectListItem> data_list = new List<SelectListItem>();
            data_list.AddRange(objblDepartamento.ListarDepartamentos(0).Select(a => new SelectListItem() { Text = a.Departamento.ToUpper(), Value = Convert.ToString(a.Id_Departamento) }));
            ViewData["ddlDepartamento"] = data_list;
            ViewData["ddlProvincia"] = new SelectList(new[] { "(Selecciona)" });
            ViewData["ddlDistrito"] = new SelectList(new[] { "(Selecciona)" });

            return PartialView("_DatosProyecto");
        }

    }
}

SIS_Ga2/Views/ProyectoDiseno/Index.cshtml
@using SIS_Ga2.Entity
@using SIS_Ga2.Controllers

@model IEnumerable<SIS_Ga2.Entity.Proyecto>
@{ 
    ViewBag.Title = "Diseno";
    BEUsuario usuario = Session["sistema.usuario"] as BEUsuario;
    BEProyecto proyecto = Session["proyecto.general"] as BEProyecto;
    Sistema sistema = Session["sistema.general"] as Sistema;
    if (sistema == null)
    {
        Response.Redirect(Url.Action("Login", "Seguridad"));
        return;
    }

    string titulo = proyecto.Id_Diseno == 0 ? "NUEVO DISEÑO" : "EDITANDO DISEÑO N.: " + proyecto.Id_Diseno;
}

<input type="hidden" id="txtidTipoDiseno" value="@sistema.idAplicacion" />
<input type="hidden" id="txtidDisenoNP" value="@proyecto.Id_Diseno" />
<input type="hidden" id="txtidUsuario" value="@sistema.idUsuario" />
<input type="hidden" id="txtUsuario" value="@usuario.Usuario" />


<div class="col-lg-12">
    <div class="card">
        <div class="card-header d-flex align-items-center">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">DISEÑO DE PAVIMENTOS - @sistema.TipoDiseno - @titulo</li>
                </ol>
            </nav>
        </div>
        <div class="accordion" id="accordionDiseno">
        </div>
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        var idTipoDiseno = document.getElementById("txtidTipoDiseno").value;

        if (idTipoDiseno == 1) {
            
            $.get('@Url.Action("IndexAsfalto", "ParametrosAsfalto")', function (data) {
                $('#accordionDiseno').html(data);
            });
        }
        else if (idTipoDiseno == 2) {
            $.get('@Url.Action("IndexAdoquin", "ParametrosAdoquin")', function (data) {
                $('#accordionDiseno').html(data);
            });
        } else {
            $.get('@Url.Action("IndexConcreto", "ParametrosConcreto")', function (data) {
                $('#accordionDiseno').html(data);
            });
        }
    });

</script>

SIS_Ga2/Views/ProyectoDiseno/_DatosProyecto.cshtml
@using SIS_Ga2.Entity
@using SIS_Ga2.Controllers

@model IEnumerable<SIS_Ga2.Entity.Proyecto>
@{
    ViewBag.Title = "Diseno";
    BEUsuario usuario = Session["sistema.usuario"] as BEUsuario;
    BEProyecto proyecto = Session["proyecto.general"] as BEProyecto;
    Sistema sistema = Session["sistema.general"] as Sistema;

    var tipodiseno = sistema.idTipoDiseno == 1 ? "ASFALTO" : sistema.idTipoDiseno == 2 ? "ADOQUIN" : "CONCRETO";

    if (sistema == null)
    {
        Response.Redirect(Url.Action("Login", "Seguridad"));
        return;
    }
}


<div class="card">
    <div class="card-header" id="headingSix">
        <h5 class="mb-0">
            <button id="btnCollapseSix" class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                DATOS DE PROYECTO
            </button>
        </h5>
    </div>
    <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionDiseno">
        <div class="card-body">
            <div class="row col-12">
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Tipo de Diseño</label>
                    <input id="hdTipoDiseno" data-id="1" type="hidden" value="@sistema.idTipoDiseno" class="column_filter mr-3 col-sm-12 form-control form-control-sm">
                    <input id="txtTipodiseno" data-id="1" type="text" placeholder="Tipo de Diseño" value="@sistema.TipoDiseno" class="column_filter mr-3 col-sm-12 form-control form-control-sm" disabled>
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Fecha Proyecto</label>
                    <input id="txtFechaProyecto" name="txtFechaProyecto" data-id="4" type="text" placeholder="Fecha Proyecto" value="@proyecto.Fecha_Proyecto_Date" class="column_filter mr-3 col-sm-12 form-control form-control-sm" disabled>
                </div>
                <div class="form-group col-md-4" style="display:none">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Fecha Contrato</label>
                    <input id="txtFechaContrato" name="txtFechaContrato" data-id="4" type="text" placeholder="Fecha Proyecto" value="@proyecto.Fecha_Contrato_Date" class="column_filter mr-3 col-sm-12 form-control form-control-sm">
                </div>
            </div>
            <div class="row col-12">
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Número de Proyecto</label>
                    <input id="txtNumProyecto" name="txtNumProyecto" data-id="1" type="text" placeholder="Número de Proyecto" class="column_filter mr-3 col-sm-12 form-control form-control-sm">
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Proyecto</label>
                    <input id="txtProyecto" name="txtProyecto" data-id="1" type="text" placeholder="Proyecto" class="column_filter mr-3 col-sm-12 form-control form-control-sm">
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Diseño</label>
                    <input id="txtDiseno" type="text" placeholder="Diseño" class="mr-3 col-sm-12 form-control form-control-sm">
                </div>
            </div>
            <div class="row col-12">
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Ingeniero</label>
                    <input id="txtIngeniero" name="txtIngeniero" data-id="4" type="text" placeholder="Ingeniero" class="column_filter mr-3 col-sm-12 form-control form-control-sm">
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Tramo</label>
                    <input id="txtTramo" type="text" placeholder="Tramo" class="mr-3 col-sm-12 form-control form-control-sm">
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Reglamento</label>
                    @Html.DropDownList("ddlReglamento", null, new { @class = "mr-3 col-sm-12 form-control form-control-sm" })
                </div>
            </div>
            <div class="row col-12">
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Departamento</label>
                    @Html.DropDownList("ddlDepartamento", null, new { @class = "mr-3 col-sm-12 form-control form-control-sm" })
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Provincia</label>
                    @Html.DropDownList("ddlProvincia", null, new { @class = "mr-3  col-sm-12 form-control form-control-sm" })
                </div>
                <div class="form-group col-md-4">
                    <label for="inlineFormInput" class="col-form-label col-form-label-sm">Distrito</label>
                    @Html.DropDownList("ddlDistrito", null, new { @class = "mr-3  col-sm-12 form-control form-control-sm" })
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class=" clearfix">
                <div class="p-0">
                    <div class="btn-group float-right" role="group" aria-label="Basic example">
                        <button type="button" id="btnGuardarProyDiseno" class="btn btn-primary small"><span class="fa fa-floppy-o"></span> Guardar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">

    $(document).ready(function ($) {

        $('#txtFechaContrato').bootstrapMaterialDatePicker({
            format: 'DD/MM/YYYY',
            shortTime: false,
            date: true,
            time: false,
            monthPicker: false,
            year: false,
            clearButton: true,
            nowButton: false,
            switchOnClick: true,
            cancelText: 'Cancelar',
            clearText: 'Limpiar',

            okText: 'OK',
            triggerEvent: 'focus',
            lang: 'es',
            weekStart: 1,

        });

        $("#ddlDepartamento").change(function () {
            cambiaDepartamento($("#ddlDepartamento").val());
        });

        $("#ddlProvincia").change(function () {
            cambiaProvincia($("#ddlProvincia").val());
        });

        var iddiseno = $("#txtidDisenoNP").val();

        if (iddiseno === "0") {
            cambiaDepartamento($("#ddlDepartamento").val());
        }
    });

    function cambiaDepartamento(idDepartamento) {

        var provincia = $("#ddlProvincia").val();
        provincia = provincia === "" || provincia === "Espere..." || provincia === "(Selecciona)" ? "0" : provincia;

        if (objProyectoDiseno.datos_proyecto.provincia.valor_selector !== "") {

            provincia = provincia === "0" ? objProyectoDiseno.datos_proyecto.provincia.valor_selector : provincia;
        }
        else
            provincia = "0";


        var dd = document.getElementById("ddlProvincia");

        dd.options.length = 0;
        dd.options[0] = new Option("Espere...");
        dd.selectedIndex = 0;
        dd.disabled = true;

        // Control de errores
        $("#ddlProvincia").ajaxError(function (event, request, settings) {
            dd.options[0] = new Option("Departamento incorrecto");
        });


        var objData = {};
        objData["idDepartamento"] = idDepartamento;

        $.ajax({
            type: "POST",
            url: '/Home/ListaProvincias',
            data: JSON.stringify(objData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (provincias) {

                var obj = (typeof provincias) == 'string' ? eval('(' + provincias + ')') : provincias;

                $.each(obj, function (i, item) {
                    dd.options[i] = new Option(item.Provincia, item.Id_Provincia);
                });

                dd.disabled = false;

                $("#ddlProvincia").val(provincia);

                cambiaProvincia(provincia);
            }

        });
    }

    function cambiaProvincia(idProvincia) {


        var distrito = $("#ddlDistrito").val();
        distrito = distrito === "" || distrito === "Espere..." || distrito === "(Selecciona)" ? "0" : distrito;

        if (objProyectoDiseno.datos_proyecto.distrito.valor_selector !== "") {

            distrito = distrito === "0" ? objProyectoDiseno.datos_proyecto.distrito.valor_selector : distrito;
        }
        else
            distrito = "0";


        var dd = document.getElementById("ddlDistrito");

        dd.options.length = 0;
        dd.options[0] = new Option("Espere...");
        dd.selectedIndex = 0;
        dd.disabled = true;

        // Control de errores
        $("#ddlDistrito").ajaxError(function (event, request, settings) {
            dd.options[0] = new Option("Distrito incorrecto");
        });


        var objData = {};
        objData["idProvincia"] = idProvincia;

        $.ajax({
            type: "POST",
            url: '/Home/ListaDistritos',
            data: JSON.stringify(objData),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (distritos) {

                var obj = (typeof distritos) == 'string' ? eval('(' + distritos + ')') : distritos;

                $.each(obj, function (i, item) {
                    dd.options[i] = new Option(item.Distrito, item.id_Distrito);
                });

                dd.disabled = false;

                $("#ddlDistrito").val(distrito);

            }

        });

    }

    function validarCamposDatosProyecto() {

       // var fechacontrato = $("#txtFechaContrato").val();
        var numproyecto = $("#txtNumProyecto").val();
        var proyecto =  $("#txtProyecto").val();
        var diseno = $("#txtDiseno").val();
        var ingeniero  = $("#txtIngeniero").val();
        var tramo = $("#txtTramo").val();
        var departamento =  $("#ddlDepartamento").val();
        var provincia = $("#ddlProvincia").val();
        var distrito = $("#ddlDistrito").val();


        //if (fechacontrato === "") {
        //    toastr.warning('El campo FECHA CONTRATO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
        //    return false;
        //}

        if (numproyecto === "") {
            toastr.warning('El campo NUMERO PROYECTO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#txtNumProyecto").focus();
            return false;
        }

        if (proyecto === "") {
            toastr.warning('El campo PROYECTO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#txtProyecto").focus();
            return false;
        }

        if (diseno === "") {
            toastr.warning('El campo DISEÑO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#txtDiseno").focus();
            return false;
        }

        if (ingeniero === "") {
            toastr.warning('El campo INGENIERO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#txtIngeniero").focus();
            return false;
        }

        if (tramo === "") {
            toastr.warning('El campo TRAMO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#txtTramo").focus();
            return false;
        }

        if (departamento === "0") {
            toastr.warning('El campo DEPARTAMENTO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#ddlDepartamento").focus();
            return false;
        }

        if (provincia === "0") {
            toastr.warning('El campo PROVINCIA es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#ddlProvincia").focus();
            return false;
        }

        if (distrito === "0") {
            toastr.warning('El campo DISTRITO es requerido', 'ADVERTENCIA', { timeOut: 2000 });
            $("#ddlDistrito").focus();
            return false;
        }

        return true;
    }

</script>